version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: cartuchos_local_django
    container_name: cartuchos_local_django
    depends_on:
      - postgres
    env_file:
      - ./.envs/.production-nginx/.django
      - ./.envs/.production-nginx/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: cartuchos_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production-nginx/.postgres

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: nginx_privated_file
    restart: on-failure:10
    depends_on:
      - django
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./mediafiles:/app/mediafiles
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"


  redis:
    image: redis:5-alpine
    restart: on-failure:5 

  celeryworker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: celery_worker
    restart: on-failure:5 
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    depends_on:
      - redis
      - postgres

  celerybeat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: celery_beat
    restart: on-failure:5 
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    depends_on:
      - redis
      - postgres

  flower:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: celey_flower
    restart: on-failure:5 
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - 5555:5555
    depends_on:
      - redis
      - postgres