version: '3'

volumes:
  cartuchos_local_postgres_data: {}
  cartuchos_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: cartuchos_local_django
    container_name: cartuchos_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: cartuchos_production_postgres
    container_name: cartuchos_local_postgres
    volumes:
      - cartuchos_local_postgres_data:/var/lib/postgresql/data:Z
      - cartuchos_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  frontend:
    build:
      context: .
      dockerfile: ./compose/staging/vuejs/Dockerfile
    volumes:
      - /app/node_modules
    ports:
      - 8080:8080