version: '3'

volumes:
  backend_local_postgres_data: {}
  backend_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: backend_local_django
    container_name: backend_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: backend_production_postgres
    container_name: backend_local_postgres
    volumes:
      - backend_local_postgres_data:/var/lib/postgresql/data:Z
      - backend_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  frontend:
    build:
      context: .
      dockerfile: ./compose/staging/vuejs/Dockerfile
    volumes:
      - /app/node_modules
    ports:
      - 8080:8080

  smtp-server:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'


  redis:
    image: redis:5-alpine
    restart: on-failure:5 

  celeryworker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: celery_worker
    restart: on-failure:5 
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    depends_on:
      - redis
      - postgres

  celerybeat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: celery_beat
    restart: on-failure:5 
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    depends_on:
      - redis
      - postgres

  flower:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: celey_flower
    restart: on-failure:5 
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - 5555:5555
    depends_on:
      - redis
      - postgres