# Generated by Django 3.2.11 on 2022-01-19 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColorReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FboCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupUnity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubFamilyIntern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cartridges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('selling_price_base', models.FloatField()),
                ('weitgh', models.IntegerField()),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clase', related_query_name='clase', to='cartridge.clase')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='color', related_query_name='color', to='cartridge.color')),
                ('color_reference', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='color_reference', related_query_name='color_reference', to='cartridge.colorreference')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='family', related_query_name='family', to='cartridge.family')),
                ('family_intern', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='family_intern', related_query_name='family_intern', to='cartridge.subfamily')),
                ('fbo_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fbo_code', related_query_name='fbo_code', to='cartridge.fbocode')),
                ('group_unity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_unity', related_query_name='group_unity', to='cartridge.groupunity')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='manufacturer', related_query_name='manufacturer', to='cartridge.manufacturer')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reference', related_query_name='reference', to='cartridge.reference')),
                ('reference_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reference_group', related_query_name='reference_group', to='cartridge.referencegroup')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='size', related_query_name='size', to='cartridge.size')),
                ('sub_family_intern', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_family_intern', related_query_name='sub_family_intern', to='cartridge.subfamilyintern')),
            ],
            options={
                'verbose_name': 'Cartucho',
                'verbose_name_plural': 'Cartuchos',
            },
        ),
    ]
