# Generated by Django 3.2.11 on 2022-01-19 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContratoFirmado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CpZip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frecuencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NombreRazonSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poblacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrincipalCIF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TarifaAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZonaGeografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cifrc', models.CharField(blank=True, max_length=255, null=True)),
                ('sucursal', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('email_respaldo', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('persona_contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('horario_recogida', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_ingreso', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_cuenta', models.CharField(blank=True, max_length=255, null=True)),
                ('proximo_aviso', models.CharField(blank=True, max_length=255, null=True)),
                ('num_ct1', models.CharField(blank=True, max_length=255, null=True)),
                ('cnae', models.CharField(blank=True, max_length=255, null=True)),
                ('mini_broker', models.CharField(blank=True, max_length=255, null=True)),
                ('nro_productor', models.CharField(blank=True, max_length=255, null=True)),
                ('campaña', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaña', related_query_name='campaña', to='clients.campaña')),
                ('cif_principal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cif_principal', related_query_name='cif_principal', to='clients.nombrerazonsocial')),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clasificacion', related_query_name='clasificacion', to='clients.clasificacion')),
                ('contrato_firmado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='nima', related_query_name='nima', to='clients.contratofirmado')),
                ('cp_zip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cp_zip', related_query_name='cp_zip', to='clients.cpzip')),
                ('frecuencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='frecuencia', related_query_name='frecuencia', to='clients.frecuencia')),
                ('nima', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='nima', related_query_name='nima', to='clients.nima')),
                ('nombre_razon_social', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='nombre_razon_social', related_query_name='nombre_razon_social', to='clients.nombrerazonsocial')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pais', related_query_name='pais', to='clients.pais')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='perfil', related_query_name='perfil', to='clients.perfil')),
                ('poblacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='settlement', related_query_name='settlement', to='clients.poblacion')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='province', related_query_name='province', to='clients.poblacion')),
                ('tarifa_asignada', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tarifa_asignada', related_query_name='tarifa_asignada', to='clients.tarifaasignada')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo', related_query_name='tipo', to='clients.tipo')),
                ('zona_geografica', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='zona_geografica', related_query_name='zona_geografica', to='clients.zonageografica')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
