# Generated by Django 3.2.11 on 2022-01-19 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_cliente_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cif_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cif_principal', related_query_name='cif_principal', to='clients.principalcif'),
        ),
    ]
