# Generated by Django 3.2.11 on 2022-02-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_cliente_cif_principal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaña',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterModelOptions(
            name='clasificacion',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterModelOptions(
            name='contratofirmado',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterModelOptions(
            name='cpzip',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterModelOptions(
            name='frecuencia',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterModelOptions(
            name='nima',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterModelOptions(
            name='nombrerazonsocial',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterModelOptions(
            name='poblacion',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterModelOptions(
            name='principalcif',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterModelOptions(
            name='tarifaasignada',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterModelOptions(
            name='tipo',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterModelOptions(
            name='zonageografica',
            options={'get_latest_by': 'created'},
        ),
        migrations.AddField(
            model_name='campaña',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='campaña',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='contratofirmado',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='contratofirmado',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='cpzip',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='cpzip',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='frecuencia',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='frecuencia',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='nima',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='nima',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='nombrerazonsocial',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='nombrerazonsocial',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='pais',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='pais',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='poblacion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='poblacion',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='principalcif',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='principalcif',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='tarifaasignada',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='tarifaasignada',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='tipo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='tipo',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='zonageografica',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='zonageografica',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at'),
        ),
    ]
