# Generated by Django 3.2.11 on 2022-01-20 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartridge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('fee', models.FloatField(blank=True, default=0, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fee', related_query_name='fee', to='cartridge.family')),
                ('sub_family_intern', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fee', related_query_name='fee', to='cartridge.subfamilyintern')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
            },
        ),
    ]
