# Generated by Django 3.2.11 on 2022-02-12 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartridge', '0002_auto_20220211_2230'),
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedcartridges',
            name='Cartridges',
        ),
        migrations.AddField(
            model_name='selectedcartridges',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selectedcartridges',
            name='selected',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='selected_cartridges', related_query_name='selected_cartridges', to='cartridge.cartridges'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selectedcartridges',
            name='weight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
