# Generated by Django 3.2.11 on 2022-02-12 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20220211_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='cartridges',
        ),
        migrations.AddField(
            model_name='selectedcartridges',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notes', related_query_name='notes', to='note.notes'),
        ),
    ]
