# Generated by Django 3.2.11 on 2022-03-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', null=True, verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('report_definition', models.TextField()),
                ('report_type', models.CharField(max_length=100, unique=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('last_modified_at', models.DateTimeField()),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', null=True, verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('key', models.CharField(max_length=36)),
                ('report_definition', models.TextField()),
                ('data', models.TextField()),
                ('is_test_data', models.BooleanField()),
                ('pdf_file', models.BinaryField(null=True)),
                ('pdf_file_size', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField()),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
